services:
  backend:
    build: ./backend
    container_name: rt3-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./data/rt3.db
      - RT3_BACKUP_DIR=${RT3_BACKUP_DIR:-/app/backup}
    volumes:
      - ./utils:/opt/rt3/utils
      - ./backend:/app
      - ./data:/app/data
      - ./nginx/certs:/app/certs
      - ./uploads:/app/uploads
      - ${RT3_BACKUP_DIR:-./backup}:/app/backup
    command: /bin/bash -c 'dos2unix /opt/rt3/utils/backend_start.sh && chmod +x /opt/rt3/utils/backend_start.sh && /opt/rt3/utils/backend_start.sh'
    networks:
      - rt3-network
    restart: unless-stopped
    dns:
      - ${CUSTOM_DNS:-8.8.8.8}
      - ${CUSTOM_DNS_SECONDARY:-8.8.4.4}

  frontend:
    build: ./frontend
    container_name: rt3-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://localhost/api
    depends_on:
      - backend
    networks:
      - rt3-network

  nginx:
    build: ./nginx
    container_name: rt3-nginx
    #ports are set in the override file or prod file
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - rt3-network
    restart: unless-stopped

networks:
  rt3-network:
    driver: bridge